name: Test build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'master'
    - name: Setup for build
      run:
        apt update
        apt install devscripts
        mk-build-deps -iry
    - name: Build
      run:
        dpkg-buildpackage


