name: Test build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'master'
    - name: Setup for build
      run: |
        sudo apt update
        sudo apt install devscripts equivs
        sudo DEBIAN_FRONTEND=noninteractive mk-build-deps -i -r -t 'apt-get -y' debian/control
    - name: Build
      run:
        dpkg-buildpackage -us -uc


