name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: mtwebster/github-actions/.github/workflows/do-builds.yml@main
    with:
      commit_id: master
